### ISSUE TITLE
Get 'inf' with to_crs

### ISSUE THREAD

**Issue by weichennone** [lukaskondmann/DENETHOR#2]
Hi,

I have a NAN problem when I use to_crs.
https://github.com/lukaskondmann/DENETHOR/blob/b3d70314b8d95a16d8ff4b8f36b90c5f067efe4f/dataset.py#L33

Traceback (most recent call last):
  File "train.py", line 294, in <module>
    train(args)
  File "train.py", line 118, in train
    train_loss = train_epoch(model, optimizer, criterion, traindataloader, device)
  File "train.py", line 195, in train_epoch
    for idx, batch in iterator:
  File "anaconda3/envs/cl/lib/python3.7/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "anaconda3/envs/cl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "anaconda3/envs/cl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "anaconda3/envs/cl/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "anaconda3/envs/cl/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "anaconda3/envs/cl/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 363, in __getitem__
    return self.dataset[self.indices[idx]]
  File "workspace/DENETHOR/dataset.py", line 68, in __getitem__
    image_stack = np.stack([rio.open(os.path.join(self.tifroot,tif)).read(window=window) for tif in self.tifs])
  File "workspace/DENETHOR/dataset.py", line 68, in <listcomp>
    image_stack = np.stack([rio.open(os.path.join(self.tifroot,tif)).read(window=window) for tif in self.tifs])
  File "rasterio/_io.pyx", line 302, in rasterio._io.DatasetReaderBase.read
  File "anaconda3/envs/cl/lib/python3.7/site-packages/rasterio/windows.py", line 664, in round_lengths
    pixel_precision is not None else self.width),
ValueError: cannot convert float NaN to integer

After I comment out this line, there is no NAN problem. But I think it's not correct to comment out the transform since the geo info should be different. 

Could you provide some ideas about this issue?

Thanks!

**Comment by lukaskondmann** [comment]
Hi, could you elaborate on the situation in which this issue arises? Are you reading in the training geojson for 2019? Ideal would be a minimal working example with the version of the respective packages you are using to replicate this. 

The [to_crs function](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.to_crs.html) is a standard geopandas function so any issue with the output may be the result of a corrupted .geojson. There are two ways to download the training data: SyncAndShare and RadiantEarth ML Hub. Does the issue still arise if you download the training .geojson from Radiant Earth's ML Hub?

**Comment by weichennone** [comment]
Hi Lukas, thank you for your quick reply! 
I found it work in a different machine (the rest are the same), not sure what's going on, but it works now.
